### ISSUE TITLE
'Logged-in check' page redirects to my user page

### ISSUE THREAD

**Issue by ghost** [derivativefx/derivativefx#3]
Previously when I used derivativeFX, I was able to check "don't bother me about this again" and click the button to continue, but now that button is greyed out and the page redirects within a couple seconds to my user page.

I am running Firefox 60.4.0esr 20181211232904,
user-agent Mozilla/5.0 (X11; Linux i686; rv:60.0) Gecko/20100101 Firefox/60.0
on PureOS 8 "Prometheus" (a fork of Debian Testing); Linux 4.9.0-8-686-pae

**Comment by Steinsplitter** [comment]
See also report here: https://commons.wikimedia.org/wiki/User_talk:Steinsplitter#DerivativeFX

The frame is causing a redirect, likely a security feature? @tgr any idea?

I mad a hotfix by skipping the first step.

**Comment by tgr** [comment]
MediaWiki pages can include Javascript for breaking out of frames as a security measure, see `OutputPage::allowClickjacking()` / `OutputPage::preventClickjacking()`. Normally it's only used when there is some action presented on the page that a user might be fooled into using, such as a patrol footer. This feature has been around for a long time; I am not aware of any recent changes.

**Comment by Steinsplitter** [comment]
^^ Thanks. Restored and ...

...fixed in d2ca47e92c7ec0e36cf965a7b89db98dd61ac79c
